# Generated by Django 3.2.6 on 2024-06-27 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'observation_category',
            },
        ),
        migrations.CreateModel(
            name='ObservationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('observation_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observation.observationcategory')),
            ],
            options={
                'db_table': 'observation_key',
            },
        ),
        migrations.CreateModel(
            name='ObservationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('observation_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observation.observationcategory')),
            ],
            options={
                'db_table': 'observation report',
            },
        ),
        migrations.CreateModel(
            name='ObservationReportKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.FloatField(default=0)),
                ('min_marks', models.FloatField(default=0)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observation.observationkey')),
                ('observation_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observation.observationreport')),
            ],
            options={
                'db_table': 'observation_report_key',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='UserReportEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(default=0)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('observation_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observation.observationreport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_report_enrollment',
            },
        ),
        migrations.CreateModel(
            name='UserReportKeyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_report_key_text', models.TextField(blank=True, null=True)),
                ('rating_text', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('observation_report_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observation.observationreportkey')),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observation.rating')),
                ('user_report_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observation.userreportenrollment')),
            ],
            options={
                'db_table': 'user_report_key_point',
            },
        ),
    ]
